# Copyright (C) 2018  Christian Berger
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

version: '2'

services:
    opendlv-device-camera-rpi-omx:
        container_name: rpi-camera-omx
        build:
            context: https://github.com/chalmers-revere/opendlv-device-camera-rpi-omx.git
            dockerfile: Dockerfile.armhf
        restart: on-failure
        network_mode: "host"
        ipc: "host"
        privileged: true
        volumes:
        - /tmp:/tmp
        command: "--cid=112 --name.argb=img.argb --width=640 --height=480 --freq=20"


    opendlv-vehicle-view-armhf:
        container_name: opendlv-vehicle-view
        image: chrberger/opendlv-vehicle-view-armhf:20180731
        restart: on-failure
        network_mode: "host"
        volumes:
        - ~/recordings:/opt/vehicle-view/recordings
        - /var/run/docker.sock:/var/run/docker.sock
        environment:
        - OD4SESSION_CID=112
        ports:
        - "8081:8081"

